<?php

namespace Database\Seeders;

use App\Models\Recipe;
use Illuminate\Database\Seeder;

class KenyanMealsSeeder extends Seeder
{
    public function run(): void
    {
        // Delete any existing recipe library data
        Recipe::where('user_id', 1)->delete();

        $userId = 1;

        $meals = array_merge(
            $this->breakfastMeals($userId),
            $this->lunchMeals($userId),
            $this->dinnerMeals($userId),
            $this->snackMeals($userId)
        );

        foreach (array_chunk($meals, 50) as $chunk) {
            Recipe::insert($chunk);
        }

        $this->command->info('✅ Inserted ' . count($meals) . ' Kenyan meals successfully.');
    }

    private function ts(): string
    {
        return now()->toDateTimeString();
    }

    private function row(
        int $userId,
        string $name,
        string $mealType,
        int $calories,
        float $protein,
        float $carbs,
        float $fat,
        float $cost,
        int $prep,
        string $ingredients,
        bool $vegetarian = false,
        bool $traditional = true,
        string $difficulty = 'Easy'
    ): array {
        return [
            'user_id' => $userId,
            'name' => $name,
            'meal_type' => $mealType,
            'country' => 'Kenya',
            'cuisine_type' => 'Kenyan',
            'calories' => $calories,
            'protein' => $protein,
            'carbs' => $carbs,
            'fat' => $fat,
            'fiber' => 5, // Default/estimated average base value
            'sugar' => 10,
            'sodium' => 200,
            'health_score' => $traditional ? 80 : 70,
            'diet_type' => $vegetarian ? 'vegetarian' : 'balanced',
            'tags' => json_encode([$traditional ? 'traditional' : 'modern']),
            'estimated_cost' => $cost,
            'prep_time_minutes' => $prep,
            'difficulty_level' => $difficulty,
            'key_ingredients' => $ingredients,
            'is_healthy' => true,
            'is_vegetarian' => $vegetarian,
            'is_traditional' => $traditional,
            'cooking_time_minutes' => $prep,
            'complexity_level' => $difficulty,
            'is_generated' => false,
            'created_at' => $this->ts(),
            'updated_at' => $this->ts(),
        ];
    }

    private function breakfastMeals(int $u): array
    {
        return [
            $this->row($u, 'Tea and Mandazi', 'breakfast', 320, 6, 55, 9, 80, 15, 'mandazi,tea,milk,sugar', true, true),
            $this->row($u, 'Tea and Chapati', 'breakfast', 380, 8, 60, 12, 70, 20, 'chapati,tea,milk,sugar', true, true),
            $this->row($u, 'Tea and Bread with Butter', 'breakfast', 280, 7, 42, 9, 60, 5, 'bread,butter,tea,milk', true, true),
            $this->row($u, 'Tea and Bread with Margarine', 'breakfast', 270, 6, 42, 8, 50, 5, 'bread,margarine,tea,milk', true, true),
            $this->row($u, 'Tea and Bread with Peanut Butter', 'breakfast', 350, 10, 44, 14, 70, 5, 'bread,peanut butter,tea,milk', true, true),
            $this->row($u, 'Tea and Boiled Eggs', 'breakfast', 240, 14, 28, 8, 90, 10, 'eggs,tea,milk,sugar', false, true),
            $this->row($u, 'Tea and Omelette', 'breakfast', 290, 16, 28, 11, 110, 15, 'eggs,onions,tomatoes,tea', false, true),
            $this->row($u, 'Tea and Sweet Potatoes', 'breakfast', 310, 5, 65, 3, 60, 20, 'sweet potatoes,tea,milk', true, true),
            $this->row($u, 'Tea and Arrowroots', 'breakfast', 290, 4, 62, 2, 50, 25, 'arrowroots,tea,milk', true, true),
            $this->row($u, 'Tea and Cassava', 'breakfast', 300, 3, 68, 1, 40, 30, 'cassava,tea,milk', true, true),
            $this->row($u, 'Tea and Maize Porridge', 'breakfast', 210, 4, 44, 2, 30, 15, 'maize flour,milk,sugar,tea', true, true),
            $this->row($u, 'Tea and Millet Porridge', 'breakfast', 220, 5, 46, 3, 35, 20, 'millet flour,milk,sugar,tea', true, true),
            $this->row($u, 'Tea and Sorghum Porridge', 'breakfast', 215, 5, 45, 3, 35, 20, 'sorghum flour,milk,sugar', true, true),
            $this->row($u, 'Tea and Groundnuts', 'breakfast', 340, 12, 30, 18, 60, 5, 'groundnuts,tea,milk,sugar', true, true),
            $this->row($u, 'Tea and Bananas', 'breakfast', 230, 4, 52, 2, 40, 5, 'bananas,tea,milk', true, true),
            $this->row($u, 'Coffee and Bread', 'breakfast', 260, 7, 40, 7, 65, 5, 'bread,coffee,milk,sugar', true, false),
            $this->row($u, 'Coffee and Pancakes', 'breakfast', 390, 9, 62, 12, 85, 20, 'flour,eggs,coffee,milk', true, false),
            $this->row($u, 'Coffee and Omelette', 'breakfast', 270, 16, 20, 12, 100, 15, 'eggs,coffee,onions,tomatoes', false, false),
            $this->row($u, 'Coffee and Mandazi', 'breakfast', 330, 6, 56, 10, 80, 15, 'mandazi,coffee,milk', true, true),
            $this->row($u, 'Coffee and Chapati', 'breakfast', 370, 8, 58, 13, 75, 20, 'chapati,coffee,milk', true, true),
            $this->row($u, 'Avocado Toast', 'breakfast', 310, 8, 32, 17, 90, 10, 'bread,avocado,salt,lemon', true, false),
            $this->row($u, 'Egg Sandwich', 'breakfast', 350, 18, 34, 15, 120, 15, 'bread,eggs,tomatoes,lettuce', false, false),
            $this->row($u, 'Boiled Eggs and Avocado', 'breakfast', 290, 14, 8, 22, 110, 12, 'eggs,avocado,salt', false, true),
            $this->row($u, 'Bread and Jam', 'breakfast', 240, 6, 44, 5, 50, 5, 'bread,jam,butter', true, true),
            $this->row($u, 'Bread and Honey', 'breakfast', 250, 6, 48, 4, 65, 5, 'bread,honey,butter', true, true),
            $this->row($u, 'Bread and Fried Eggs', 'breakfast', 320, 15, 36, 13, 100, 12, 'bread,eggs,cooking oil', false, true),
            $this->row($u, 'Bread and Sausage', 'breakfast', 380, 18, 34, 18, 150, 15, 'bread,sausage,ketchup', false, false),
            $this->row($u, 'Chapati and Beans', 'breakfast', 420, 16, 68, 8, 90, 25, 'chapati,beans,onions,tomatoes', true, true),
            $this->row($u, 'Chapati and Eggs', 'breakfast', 400, 18, 58, 13, 110, 20, 'chapati,eggs,tomatoes', false, true),
            $this->row($u, 'Chapati and Vegetables', 'breakfast', 360, 10, 58, 10, 80, 20, 'chapati,cabbage,carrots,onions', true, true),
            $this->row($u, 'Pancakes and Honey', 'breakfast', 380, 9, 64, 10, 90, 20, 'flour,eggs,honey,milk', true, false),
            $this->row($u, 'Pancakes and Syrup', 'breakfast', 400, 9, 70, 10, 95, 20, 'flour,eggs,syrup,milk', true, false),
            $this->row($u, 'Pancakes and Fruits', 'breakfast', 370, 9, 66, 9, 100, 20, 'flour,eggs,banana,mango,milk', true, false),
            $this->row($u, 'Millet Porridge with Milk', 'breakfast', 260, 8, 48, 5, 50, 20, 'millet,milk,sugar', true, true),
            $this->row($u, 'Oatmeal Porridge', 'breakfast', 250, 8, 42, 5, 60, 10, 'oats,milk,sugar', true, false),
            $this->row($u, 'Oatmeal with Bananas', 'breakfast', 290, 9, 52, 5, 70, 10, 'oats,banana,milk', true, false),
            $this->row($u, 'Oatmeal with Honey', 'breakfast', 270, 8, 48, 5, 75, 10, 'oats,honey,milk', true, false),
            $this->row($u, 'Fruit Salad Breakfast', 'breakfast', 180, 3, 42, 1, 80, 10, 'banana,mango,pineapple,papaya', true, false),
            $this->row($u, 'Yogurt and Granola', 'breakfast', 310, 12, 48, 7, 120, 5, 'yogurt,granola,honey', true, false),
            $this->row($u, 'Yogurt and Fruits', 'breakfast', 260, 10, 42, 4, 110, 5, 'yogurt,banana,mango,pineapple', true, false),
            $this->row($u, 'Banana Smoothie', 'breakfast', 240, 6, 50, 3, 70, 5, 'banana,milk,honey,yogurt', true, false),
            $this->row($u, 'Mango Smoothie', 'breakfast', 230, 5, 48, 2, 80, 5, 'mango,milk,honey', true, false),
            $this->row($u, 'Avocado Smoothie', 'breakfast', 290, 6, 30, 16, 90, 5, 'avocado,milk,honey,banana', true, false),
            $this->row($u, 'Peanut Butter Smoothie', 'breakfast', 360, 14, 40, 16, 90, 5, 'peanut butter,banana,milk', true, false),
            $this->row($u, 'Sweet Potatoes and Avocado', 'breakfast', 320, 5, 52, 12, 80, 25, 'sweet potatoes,avocado,salt', true, true),
            $this->row($u, 'Cassava and Tea', 'breakfast', 290, 3, 64, 2, 45, 30, 'cassava,tea,milk', true, true),
            $this->row($u, 'Arrowroots and Eggs', 'breakfast', 300, 14, 52, 8, 100, 25, 'arrowroots,eggs,salt', false, true),
            $this->row($u, 'Arrowroots and Avocado', 'breakfast', 280, 4, 52, 10, 75, 25, 'arrowroots,avocado,salt', true, true),
            $this->row($u, 'Fried Eggs and Toast', 'breakfast', 320, 16, 32, 14, 110, 10, 'bread,eggs,cooking oil,tomatoes', false, true),
            $this->row($u, 'Scrambled Eggs and Toast', 'breakfast', 310, 16, 32, 13, 105, 10, 'bread,eggs,butter,milk', false, true),
            $this->row($u, 'Omelette with Vegetables', 'breakfast', 260, 16, 12, 16, 110, 15, 'eggs,spinach,onions,tomatoes,peppers', false, false),
            $this->row($u, 'Omelette with Cheese', 'breakfast', 310, 20, 8, 22, 160, 15, 'eggs,cheese,onions,tomatoes', false, false),
            $this->row($u, 'Omelette with Spinach', 'breakfast', 240, 16, 8, 16, 100, 15, 'eggs,spinach,onions,garlic', false, false),
            $this->row($u, 'Omelette and Chapati', 'breakfast', 450, 20, 58, 16, 130, 25, 'chapati,eggs,tomatoes,onions', false, true),
            $this->row($u, 'Mandazi and Milk', 'breakfast', 340, 10, 54, 9, 75, 15, 'mandazi,milk,sugar', true, true),
            $this->row($u, 'Mandazi and Yogurt', 'breakfast', 330, 12, 52, 8, 90, 15, 'mandazi,yogurt', true, true),
            $this->row($u, 'Chapati and Tea', 'breakfast', 340, 8, 52, 11, 65, 20, 'chapati,tea,milk,sugar', true, true),
            $this->row($u, 'Chapati and Milk', 'breakfast', 380, 12, 54, 13, 75, 20, 'chapati,milk,sugar', true, true),
            $this->row($u, 'Chapati and Honey', 'breakfast', 390, 8, 64, 11, 80, 20, 'chapati,honey', true, true),
            $this->row($u, 'Chapati and Peanut Butter', 'breakfast', 440, 14, 60, 18, 85, 20, 'chapati,peanut butter', true, true),
            $this->row($u, 'Chapati and Avocado', 'breakfast', 410, 9, 56, 18, 85, 20, 'chapati,avocado,salt,lemon', true, true),
            $this->row($u, 'Oatmeal with Peanut Butter', 'breakfast', 330, 14, 44, 12, 80, 10, 'oats,peanut butter,milk,honey', true, false),
            $this->row($u, 'Oatmeal with Apple', 'breakfast', 270, 8, 50, 4, 70, 10, 'oats,apple,milk,cinnamon', true, false),
            $this->row($u, 'Oatmeal with Cinnamon', 'breakfast', 245, 8, 44, 4, 60, 10, 'oats,milk,cinnamon,honey', true, false),
            $this->row($u, 'Yogurt Parfait', 'breakfast', 300, 12, 48, 6, 130, 5, 'yogurt,granola,banana,honey', true, false),
            $this->row($u, 'Fruit Smoothie Bowl', 'breakfast', 280, 8, 54, 4, 120, 10, 'banana,mango,yogurt,granola', true, false),
            $this->row($u, 'Granola and Milk', 'breakfast', 310, 9, 52, 8, 90, 5, 'granola,milk,honey', true, false),
            $this->row($u, 'Banana and Peanut Butter', 'breakfast', 310, 10, 42, 14, 80, 5, 'banana,peanut butter', true, false),
            $this->row($u, 'Pineapple Fruit Bowl', 'breakfast', 160, 2, 40, 1, 60, 5, 'pineapple,passion fruit,lemon', true, false),
            $this->row($u, 'Watermelon Breakfast Bowl', 'breakfast', 120, 2, 28, 1, 50, 5, 'watermelon,lime,mint', true, false),
            $this->row($u, 'Mango Fruit Bowl', 'breakfast', 150, 2, 36, 1, 70, 5, 'mango,passion fruit,lime', true, false),
            $this->row($u, 'Mixed Fruit Breakfast', 'breakfast', 200, 3, 46, 1, 90, 10, 'banana,mango,pineapple,papaya,passion fruit', true, false),
            $this->row($u, 'Healthy Breakfast Smoothie', 'breakfast', 250, 8, 46, 4, 100, 5, 'banana,spinach,yogurt,honey,milk', true, false),
            $this->row($u, 'Boiled Maize and Tea', 'breakfast', 280, 7, 56, 4, 40, 30, 'maize,tea,milk,sugar', true, true),
            $this->row($u, 'Boiled Maize and Beans', 'breakfast', 360, 15, 64, 4, 60, 35, 'maize,beans,onions,tomatoes', true, true),
            $this->row($u, 'Toast and Avocado', 'breakfast', 290, 7, 32, 15, 85, 8, 'bread,avocado,lemon,salt', true, false),
            $this->row($u, 'Toast and Eggs', 'breakfast', 300, 16, 32, 12, 100, 10, 'bread,eggs,butter', false, true),
            $this->row($u, 'Toast and Beans', 'breakfast', 340, 14, 56, 5, 80, 10, 'bread,beans,tomatoes,onions', true, true),
            $this->row($u, 'Toast and Honey', 'breakfast', 240, 6, 44, 4, 65, 5, 'bread,honey,butter', true, true),
            $this->row($u, 'Toast and Peanut Butter', 'breakfast', 320, 10, 42, 14, 70, 5, 'bread,peanut butter', true, true),
            $this->row($u, 'Vegetable Sandwich', 'breakfast', 300, 10, 40, 10, 90, 10, 'bread,lettuce,tomatoes,cucumber,avocado', true, false),
            $this->row($u, 'Egg and Avocado Sandwich', 'breakfast', 380, 18, 34, 20, 130, 15, 'bread,eggs,avocado,tomatoes,lettuce', false, false),
            $this->row($u, 'Peanut Butter Banana Sandwich', 'breakfast', 350, 10, 52, 14, 75, 5, 'bread,peanut butter,banana,honey', true, false),
            $this->row($u, 'Pancakes and Bananas', 'breakfast', 380, 9, 66, 9, 90, 20, 'flour,eggs,banana,milk,honey', true, false),
            $this->row($u, 'Pancakes and Yogurt', 'breakfast', 370, 12, 60, 10, 100, 20, 'flour,eggs,yogurt,milk', true, false),
            $this->row($u, 'Pancakes and Peanut Butter', 'breakfast', 440, 14, 62, 16, 100, 20, 'flour,eggs,peanut butter,milk', true, false),
            $this->row($u, 'Oatmeal with Berries', 'breakfast', 260, 8, 46, 4, 90, 10, 'oats,strawberries,blueberries,milk', true, false),
            $this->row($u, 'Oatmeal with Milk', 'breakfast', 240, 8, 42, 4, 55, 10, 'oats,milk,sugar', true, false),
            $this->row($u, 'Granola and Yogurt', 'breakfast', 310, 12, 50, 7, 120, 5, 'granola,yogurt,honey,banana', true, false),
            $this->row($u, 'Breakfast Wrap', 'breakfast', 370, 18, 40, 14, 130, 15, 'chapati,eggs,tomatoes,spinach,cheese', false, false),
            $this->row($u, 'Chapati and Lentils', 'breakfast', 430, 18, 68, 8, 90, 30, 'chapati,lentils,onions,tomatoes,spices', true, true),
        ];
    }

    private function lunchMeals(int $u): array
    {
        return [
            $this->row($u, 'Ugali and Sukuma Wiki', 'lunch', 480, 12, 82, 8, 80, 30, 'ugali,sukuma wiki,onions,tomatoes,cooking oil', true, true),
            $this->row($u, 'Ugali and Cabbage', 'lunch', 460, 10, 82, 6, 70, 30, 'ugali,cabbage,onions,tomatoes', true, true),
            $this->row($u, 'Ugali and Spinach', 'lunch', 450, 12, 80, 6, 75, 30, 'ugali,spinach,onions,garlic,tomatoes', true, true),
            $this->row($u, 'Ugali and Chicken Stew', 'lunch', 620, 38, 80, 14, 160, 45, 'ugali,chicken,tomatoes,onions,garlic,spices', false, true),
            $this->row($u, 'Ugali and Beef Stew', 'lunch', 650, 36, 78, 18, 170, 50, 'ugali,beef,tomatoes,onions,potatoes,spices', false, true),
            $this->row($u, 'Ugali and Fish', 'lunch', 560, 34, 78, 10, 140, 35, 'ugali,tilapia,tomatoes,onions,lemon', false, true),
            $this->row($u, 'Ugali and Beans', 'lunch', 520, 18, 90, 6, 80, 35, 'ugali,beans,tomatoes,onions,spices', true, true),
            $this->row($u, 'Ugali and Lentils', 'lunch', 510, 18, 88, 5, 75, 35, 'ugali,lentils,tomatoes,onions,garlic', true, true),
            $this->row($u, 'Ugali and Green Grams', 'lunch', 500, 16, 88, 5, 80, 35, 'ugali,green grams,tomatoes,onions,coconut milk', true, true),
            $this->row($u, 'Ugali and Goat Meat', 'lunch', 640, 35, 76, 20, 180, 55, 'ugali,goat,tomatoes,onions,garlic,spices', false, true),
            $this->row($u, 'Ugali and Liver', 'lunch', 560, 36, 76, 14, 130, 30, 'ugali,liver,onions,tomatoes,garlic', false, true),
            $this->row($u, 'Ugali and Fried Eggs', 'lunch', 540, 22, 80, 16, 110, 25, 'ugali,eggs,tomatoes,onions,cooking oil', false, true),
            $this->row($u, 'Ugali and Omena', 'lunch', 520, 28, 78, 10, 90, 30, 'ugali,omena,tomatoes,onions,garlic', false, true),
            $this->row($u, 'Ugali and Groundnut Sauce', 'lunch', 580, 16, 86, 16, 80, 30, 'ugali,groundnuts,tomatoes,onions', true, true),
            $this->row($u, 'Ugali and Vegetable Mix', 'lunch', 460, 10, 82, 6, 80, 30, 'ugali,cabbage,carrots,spinach,onions', true, true),
            $this->row($u, 'Ugali and Nyama Choma', 'lunch', 720, 45, 76, 28, 220, 60, 'ugali,goat,charcoal,lemon,salt', false, true),
            $this->row($u, 'Ugali and Tilapia', 'lunch', 580, 36, 78, 12, 150, 40, 'ugali,tilapia,tomatoes,onions,lemon,cooking oil', false, true),
            $this->row($u, 'Ugali and Sardines', 'lunch', 540, 30, 78, 12, 100, 30, 'ugali,sardines,tomatoes,onions', false, true),
            $this->row($u, 'Ugali and Pumpkin Leaves', 'lunch', 440, 10, 80, 6, 65, 30, 'ugali,pumpkin leaves,onions,tomatoes', true, true),
            $this->row($u, 'Ugali and Kunde', 'lunch', 450, 12, 80, 6, 70, 30, 'ugali,kunde,onions,tomatoes,coconut milk', true, true),
            $this->row($u, 'Githeri', 'lunch', 440, 16, 78, 6, 70, 50, 'maize,beans,onions,tomatoes,cooking oil', true, true),
            $this->row($u, 'Githeri with Avocado', 'lunch', 500, 16, 80, 14, 90, 50, 'maize,beans,avocado,tomatoes,onions', true, true),
            $this->row($u, 'Githeri with Beef', 'lunch', 580, 28, 78, 14, 140, 55, 'maize,beans,beef,tomatoes,onions', false, true),
            $this->row($u, 'Githeri with Cabbage', 'lunch', 460, 16, 80, 6, 75, 50, 'maize,beans,cabbage,tomatoes,onions', true, true),
            $this->row($u, 'Githeri with Spinach', 'lunch', 450, 16, 78, 6, 75, 50, 'maize,beans,spinach,tomatoes,onions', true, true),
            $this->row($u, 'Githeri with Potatoes', 'lunch', 500, 16, 90, 6, 80, 55, 'maize,beans,potatoes,tomatoes,onions', true, true),
            $this->row($u, 'Rice and Beans', 'lunch', 500, 16, 90, 5, 80, 35, 'rice,beans,tomatoes,onions,cooking oil', true, true),
            $this->row($u, 'Rice and Chicken Stew', 'lunch', 620, 38, 86, 14, 160, 45, 'rice,chicken,tomatoes,onions,garlic,spices', false, true),
            $this->row($u, 'Rice and Beef Stew', 'lunch', 640, 36, 86, 16, 170, 50, 'rice,beef,tomatoes,onions,potatoes', false, true),
            $this->row($u, 'Rice and Fish', 'lunch', 540, 34, 82, 8, 140, 35, 'rice,fish,tomatoes,onions,lemon', false, true),
            $this->row($u, 'Rice and Lentils', 'lunch', 510, 18, 90, 5, 80, 35, 'rice,lentils,onions,garlic,spices', true, true),
            $this->row($u, 'Rice and Green Grams', 'lunch', 500, 16, 90, 5, 85, 35, 'rice,green grams,tomatoes,onions,coconut milk', true, true),
            $this->row($u, 'Rice and Vegetable Curry', 'lunch', 490, 10, 88, 8, 90, 35, 'rice,potatoes,carrots,peppers,curry spices', true, false),
            $this->row($u, 'Pilau', 'lunch', 560, 24, 86, 12, 150, 60, 'rice,beef,pilau spices,onions,garlic', false, true),
            $this->row($u, 'Pilau and Kachumbari', 'lunch', 580, 24, 88, 12, 160, 60, 'rice,beef,pilau spices,onions,tomatoes,lemon', false, true),
            $this->row($u, 'Chicken Pilau', 'lunch', 580, 36, 84, 12, 170, 60, 'rice,chicken,pilau spices,onions,garlic', false, true),
            $this->row($u, 'Beef Pilau', 'lunch', 600, 30, 86, 14, 165, 65, 'rice,beef,pilau spices,onions,garlic', false, true),
            $this->row($u, 'Vegetable Pilau', 'lunch', 490, 10, 88, 8, 110, 50, 'rice,potatoes,carrots,raisins,pilau spices', true, true),
            $this->row($u, 'Coconut Rice and Fish', 'lunch', 560, 30, 86, 10, 160, 40, 'rice,coconut milk,fish,onions,garlic', false, true),
            $this->row($u, 'Coconut Rice and Beans', 'lunch', 510, 14, 92, 9, 110, 40, 'rice,coconut milk,beans,onions', true, true),
            $this->row($u, 'Coconut Rice and Vegetables', 'lunch', 480, 8, 90, 9, 100, 40, 'rice,coconut milk,vegetables,spices', true, false),
            $this->row($u, 'Fried Rice and Chicken', 'lunch', 560, 30, 80, 14, 160, 40, 'rice,chicken,eggs,onions,soy sauce', false, false),
            $this->row($u, 'Fried Rice and Vegetables', 'lunch', 460, 10, 82, 10, 100, 35, 'rice,carrots,peas,cabbage,eggs,soy sauce', true, false),
            $this->row($u, 'Fried Rice and Eggs', 'lunch', 480, 16, 80, 12, 110, 30, 'rice,eggs,onions,soy sauce,vegetables', false, false),
            $this->row($u, 'Chapati and Beans', 'lunch', 480, 16, 76, 8, 90, 30, 'chapati,beans,onions,tomatoes,spices', true, true),
            $this->row($u, 'Chapati and Beef Stew', 'lunch', 580, 30, 70, 18, 170, 40, 'chapati,beef,tomatoes,onions,potatoes', false, true),
            $this->row($u, 'Chapati and Chicken Stew', 'lunch', 560, 34, 70, 14, 160, 40, 'chapati,chicken,tomatoes,onions,garlic', false, true),
            $this->row($u, 'Chapati and Lentils', 'lunch', 480, 16, 76, 8, 90, 35, 'chapati,lentils,onions,tomatoes,cumin', true, true),
            $this->row($u, 'Chapati and Vegetables', 'lunch', 440, 10, 70, 10, 80, 30, 'chapati,cabbage,carrots,onions,tomatoes', true, true),
            $this->row($u, 'Chapati and Green Grams', 'lunch', 470, 14, 74, 8, 90, 35, 'chapati,green grams,coconut milk,onions', true, true),
            $this->row($u, 'Chapati and Eggs', 'lunch', 460, 18, 66, 16, 120, 25, 'chapati,eggs,tomatoes,onions', false, true),
            $this->row($u, 'Chapati and Fish', 'lunch', 520, 30, 68, 10, 140, 35, 'chapati,tilapia,tomatoes,onions,lemon', false, true),
            $this->row($u, 'Chapati and Omena', 'lunch', 480, 26, 68, 10, 100, 30, 'chapati,omena,tomatoes,onions', false, true),
            $this->row($u, 'Chapati and Cabbage', 'lunch', 420, 10, 68, 8, 70, 25, 'chapati,cabbage,onions,tomatoes', true, true),
            $this->row($u, 'Chapati and Spinach', 'lunch', 430, 12, 68, 9, 75, 25, 'chapati,spinach,onions,garlic,tomatoes', true, true),
            $this->row($u, 'Chapati and Potatoes', 'lunch', 460, 8, 78, 10, 80, 30, 'chapati,potatoes,onions,tomatoes,spices', true, true),
            $this->row($u, 'Chapati and Liver', 'lunch', 500, 30, 66, 16, 130, 30, 'chapati,liver,onions,tomatoes,garlic', false, true),
            $this->row($u, 'Mukimo and Beef', 'lunch', 600, 34, 82, 14, 180, 50, 'mukimo,beef,potatoes,maize,peas,tomatoes', false, true),
            $this->row($u, 'Mukimo and Chicken', 'lunch', 580, 36, 80, 12, 180, 50, 'mukimo,chicken,potatoes,maize,peas', false, true),
            $this->row($u, 'Mukimo and Vegetables', 'lunch', 480, 12, 84, 8, 90, 45, 'mukimo,potatoes,maize,peas,spinach', true, true),
            $this->row($u, 'Mukimo and Fish', 'lunch', 540, 32, 80, 10, 150, 45, 'mukimo,tilapia,potatoes,maize', false, true),
            $this->row($u, 'Mukimo and Eggs', 'lunch', 540, 20, 80, 14, 130, 40, 'mukimo,eggs,potatoes,maize,peas', false, true),
            $this->row($u, 'Mukimo and Cabbage', 'lunch', 470, 12, 82, 8, 85, 45, 'mukimo,cabbage,potatoes,maize,peas', true, true),
            $this->row($u, 'Mukimo and Lentils', 'lunch', 510, 16, 88, 6, 90, 50, 'mukimo,lentils,potatoes,maize,peas', true, true),
            $this->row($u, 'Mukimo and Green Grams', 'lunch', 500, 14, 88, 6, 90, 50, 'mukimo,green grams,potatoes,maize', true, true),
            $this->row($u, 'Spaghetti and Beef', 'lunch', 560, 28, 76, 14, 160, 35, 'spaghetti,beef mince,tomatoes,onions,garlic', false, false),
            $this->row($u, 'Spaghetti and Chicken', 'lunch', 540, 30, 76, 10, 160, 35, 'spaghetti,chicken,tomatoes,onions,garlic', false, false),
            $this->row($u, 'Spaghetti and Tomato Sauce', 'lunch', 440, 14, 78, 8, 90, 25, 'spaghetti,tomatoes,onions,garlic,basil', true, false),
            $this->row($u, 'Spaghetti and Vegetables', 'lunch', 430, 12, 78, 8, 100, 30, 'spaghetti,zucchini,peppers,tomatoes,onions,garlic', true, false),
            $this->row($u, 'Macaroni and Beef', 'lunch', 560, 28, 74, 14, 160, 35, 'macaroni,beef mince,tomatoes,onions,garlic', false, false),
            $this->row($u, 'Macaroni and Chicken', 'lunch', 540, 30, 74, 10, 160, 35, 'macaroni,chicken,tomatoes,onions', false, false),
            $this->row($u, 'Macaroni and Vegetables', 'lunch', 430, 12, 76, 8, 100, 30, 'macaroni,tomatoes,peppers,onions,garlic', true, false),
            $this->row($u, 'Macaroni and Cheese', 'lunch', 520, 18, 76, 16, 140, 25, 'macaroni,cheddar cheese,milk,butter,flour', true, false),
            $this->row($u, 'Beef Stew and Rice', 'lunch', 620, 34, 86, 16, 180, 50, 'rice,beef,potatoes,tomatoes,onions,spices', false, true),
            $this->row($u, 'Chicken Stew and Rice', 'lunch', 600, 36, 84, 12, 170, 45, 'rice,chicken,tomatoes,onions,garlic,spices', false, true),
            $this->row($u, 'Fish Stew and Rice', 'lunch', 540, 32, 84, 8, 150, 40, 'rice,tilapia,tomatoes,onions,lemon,spices', false, true),
            $this->row($u, 'Lentils Stew and Rice', 'lunch', 510, 18, 90, 5, 90, 40, 'rice,lentils,onions,tomatoes,garlic,spices', true, true),
            $this->row($u, 'Beans Stew and Rice', 'lunch', 520, 16, 92, 5, 85, 40, 'rice,beans,tomatoes,onions,cooking oil', true, true),
            $this->row($u, 'Vegetable Stew and Rice', 'lunch', 480, 10, 88, 8, 90, 35, 'rice,potatoes,carrots,peas,tomatoes', true, true),
            $this->row($u, 'Lentil Dhal and Chapati', 'lunch', 490, 18, 74, 8, 90, 35, 'chapati,lentils,tomatoes,onions,cumin,turmeric', true, true),
            $this->row($u, 'Chickpea Curry and Rice', 'lunch', 510, 16, 88, 10, 110, 35, 'rice,chickpeas,tomatoes,onions,curry spices', true, false),
            $this->row($u, 'Potato Stew and Chapati', 'lunch', 460, 8, 76, 10, 80, 30, 'chapati,potatoes,tomatoes,onions,spices', true, true),
            $this->row($u, 'Potato Stew and Rice', 'lunch', 480, 8, 88, 8, 80, 30, 'rice,potatoes,tomatoes,onions,spices', true, true),
            $this->row($u, 'Egg Curry and Rice', 'lunch', 510, 18, 82, 14, 110, 35, 'rice,eggs,tomatoes,onions,curry spices', false, false),
            $this->row($u, 'Vegetable Curry and Rice', 'lunch', 490, 10, 88, 8, 100, 35, 'rice,potatoes,peas,carrots,curry spices', true, false),
            $this->row($u, 'Vegetable Curry and Chapati', 'lunch', 470, 10, 74, 10, 100, 35, 'chapati,potatoes,peas,carrots,curry spices', true, false),
            $this->row($u, 'Grilled Fish and Ugali', 'lunch', 580, 36, 78, 12, 160, 40, 'ugali,tilapia,lemon,garlic,herbs', false, true),
            $this->row($u, 'Fried Fish and Ugali', 'lunch', 600, 34, 78, 18, 150, 30, 'ugali,tilapia,cooking oil,lemon,onions', false, true),
            $this->row($u, 'Beef Fry and Ugali', 'lunch', 660, 36, 76, 22, 180, 35, 'ugali,beef,onions,peppers,garlic,soy sauce', false, false),
            $this->row($u, 'Chicken Fry and Ugali', 'lunch', 620, 36, 76, 18, 170, 35, 'ugali,chicken,onions,garlic,ginger,soy sauce', false, false),
            $this->row($u, 'Goat Fry and Ugali', 'lunch', 680, 38, 76, 24, 200, 45, 'ugali,goat,onions,garlic,cumin,coriander', false, true),
            $this->row($u, 'Liver Fry and Ugali', 'lunch', 580, 38, 76, 16, 140, 30, 'ugali,liver,onions,garlic,tomatoes', false, true),
            $this->row($u, 'Beans and Sweet Potatoes', 'lunch', 430, 14, 80, 4, 70, 35, 'sweet potatoes,beans,onions,tomatoes', true, true),
            $this->row($u, 'Beans and Cassava', 'lunch', 420, 14, 80, 4, 60, 40, 'cassava,beans,onions,tomatoes', true, true),
            $this->row($u, 'Green Grams and Rice', 'lunch', 490, 16, 88, 5, 85, 35, 'rice,green grams,coconut milk,onions', true, true),
            $this->row($u, 'Green Grams and Ugali', 'lunch', 480, 16, 84, 5, 80, 35, 'ugali,green grams,coconut milk,onions,garlic', true, true),
            $this->row($u, 'Lentils and Rice', 'lunch', 500, 18, 90, 4, 80, 35, 'rice,lentils,onions,garlic,turmeric', true, true),
            $this->row($u, 'Lentils and Chapati', 'lunch', 480, 18, 76, 6, 85, 35, 'chapati,lentils,onions,garlic,cumin', true, true),
            $this->row($u, 'Mixed Vegetable Stew and Rice', 'lunch', 470, 10, 86, 8, 90, 35, 'rice,cabbage,carrots,peas,tomatoes,onions', true, true),
            $this->row($u, 'Mixed Vegetable Stew and Chapati', 'lunch', 450, 10, 74, 10, 90, 35, 'chapati,cabbage,carrots,peas,tomatoes', true, true),
            $this->row($u, 'Mixed Vegetable Stew and Ugali', 'lunch', 460, 10, 80, 8, 85, 35, 'ugali,cabbage,carrots,peas,tomatoes,onions', true, true),
            $this->row($u, 'Coconut Bean Stew and Rice', 'lunch', 520, 16, 92, 9, 110, 40, 'rice,beans,coconut milk,onions,garlic,turmeric', true, true),
            $this->row($u, 'Swahili Fish Curry and Rice', 'lunch', 560, 30, 84, 10, 170, 40, 'rice,fish,coconut milk,tomatoes,ginger,garlic,spices', false, true),
            $this->row($u, 'Peas and Potato Curry and Rice', 'lunch', 490, 10, 90, 8, 90, 35, 'rice,peas,potatoes,tomatoes,curry spices', true, false),
            $this->row($u, 'Chapati and Goat Stew', 'lunch', 600, 34, 70, 20, 190, 60, 'chapati,goat,tomatoes,onions,garlic,spices', false, true),
            $this->row($u, 'Ugali and Matumbo', 'lunch', 540, 30, 78, 14, 120, 40, 'ugali,matumbo,tomatoes,onions,garlic', false, true),
            $this->row($u, 'Wali wa Nazi and Kuku', 'lunch', 620, 36, 84, 14, 180, 50, 'rice,coconut milk,chicken,onions,garlic,spices', false, true),
        ];
    }

    private function dinnerMeals(int $u): array
    {
        return [
            $this->row($u, 'Ugali and Sukuma Wiki (Dinner)', 'dinner', 460, 12, 80, 7, 75, 30, 'ugali,sukuma wiki,onions,tomatoes', true, true),
            $this->row($u, 'Rice and Beans (Dinner)', 'dinner', 480, 16, 88, 5, 80, 35, 'rice,beans,tomatoes,onions', true, true),
            $this->row($u, 'Chapati and Lentils (Dinner)', 'dinner', 460, 16, 74, 7, 85, 35, 'chapati,lentils,onions,tomatoes,cumin', true, true),
            $this->row($u, 'Githeri (Dinner)', 'dinner', 420, 16, 76, 5, 70, 50, 'maize,beans,onions,tomatoes', true, true),
            $this->row($u, 'Mukimo and Vegetables (Dinner)', 'dinner', 460, 12, 82, 7, 85, 45, 'mukimo,peas,spinach,potatoes,maize', true, true),
            $this->row($u, 'Rice and Vegetable Curry (Dinner)', 'dinner', 470, 10, 86, 8, 90, 35, 'rice,potatoes,carrots,curry spices', true, false),
            $this->row($u, 'Spaghetti and Tomato Sauce (Dinner)', 'dinner', 420, 14, 76, 7, 90, 25, 'spaghetti,tomatoes,onions,garlic,basil', true, false),
            $this->row($u, 'Chapati and Eggs (Dinner)', 'dinner', 440, 18, 64, 16, 110, 20, 'chapati,eggs,tomatoes,onions', false, true),
            $this->row($u, 'Ugali and Fish (Dinner)', 'dinner', 540, 34, 76, 10, 140, 35, 'ugali,tilapia,tomatoes,onions,lemon', false, true),
            $this->row($u, 'Rice and Chicken Stew (Dinner)', 'dinner', 590, 36, 82, 12, 160, 45, 'rice,chicken,tomatoes,onions,garlic,spices', false, true),
            $this->row($u, 'Sweet Potatoes and Vegetables', 'dinner', 360, 8, 70, 6, 65, 25, 'sweet potatoes,sukuma wiki,onions,tomatoes', true, true),
            $this->row($u, 'Boiled Cassava and Beans', 'dinner', 410, 14, 78, 4, 60, 40, 'cassava,beans,onions,tomatoes', true, true),
            $this->row($u, 'Arrowroots and Lentils', 'dinner', 390, 14, 76, 4, 70, 35, 'arrowroots,lentils,onions,tomatoes', true, true),
            $this->row($u, 'Vegetable Stir Fry and Rice', 'dinner', 440, 10, 82, 8, 90, 25, 'rice,cabbage,carrots,broccoli,soy sauce', true, false),
            $this->row($u, 'Lentil Soup and Bread', 'dinner', 380, 16, 62, 6, 80, 25, 'lentils,bread,tomatoes,onions,garlic,spices', true, false),
            $this->row($u, 'Chicken Soup and Bread', 'dinner', 420, 30, 50, 10, 160, 40, 'chicken,bread,carrots,onions,garlic,herbs', false, false),
            $this->row($u, 'Bean Soup and Bread', 'dinner', 380, 14, 64, 5, 75, 35, 'beans,bread,onions,tomatoes,spices', true, true),
            $this->row($u, 'Vegetable Soup and Toast', 'dinner', 300, 8, 54, 6, 70, 25, 'cabbage,carrots,tomatoes,bread,onions,garlic', true, false),
            $this->row($u, 'Fried Eggs and Vegetables', 'dinner', 280, 16, 16, 16, 100, 15, 'eggs,spinach,tomatoes,onions,peppers', false, true),
            $this->row($u, 'Rice and Spinach Stew', 'dinner', 440, 10, 84, 6, 80, 30, 'rice,spinach,tomatoes,onions,garlic', true, true),
            $this->row($u, 'Ugali and Beef Stew (Dinner)', 'dinner', 620, 34, 76, 18, 170, 50, 'ugali,beef,tomatoes,onions,potatoes', false, true),
            $this->row($u, 'Ugali and Chicken Stew (Dinner)', 'dinner', 600, 36, 78, 14, 160, 45, 'ugali,chicken,tomatoes,onions,garlic', false, true),
            $this->row($u, 'Chapati and Chicken Stew (Dinner)', 'dinner', 540, 32, 68, 14, 160, 40, 'chapati,chicken,tomatoes,onions,garlic', false, true),
            $this->row($u, 'Chapati and Beef Stew (Dinner)', 'dinner', 560, 28, 68, 18, 170, 45, 'chapati,beef,potatoes,tomatoes,onions', false, true),
            $this->row($u, 'Pilau (Dinner)', 'dinner', 540, 24, 84, 12, 150, 60, 'rice,beef,pilau spices,onions,garlic', false, true),
            $this->row($u, 'Coconut Rice and Fish (Dinner)', 'dinner', 540, 30, 84, 10, 160, 40, 'rice,coconut milk,tilapia,onions,garlic', false, true),
            $this->row($u, 'Lentils and Ugali (Dinner)', 'dinner', 490, 18, 86, 5, 80, 35, 'ugali,lentils,tomatoes,onions,garlic', true, true),
            $this->row($u, 'Green Grams and Ugali (Dinner)', 'dinner', 470, 16, 82, 5, 80, 35, 'ugali,green grams,coconut milk,onions', true, true),
            $this->row($u, 'Ugali and Omed (Omena) Dinner', 'dinner', 500, 28, 76, 10, 90, 30, 'ugali,omena,tomatoes,onions,garlic', false, true),
            $this->row($u, 'Githeri with Beef (Dinner)', 'dinner', 560, 28, 76, 14, 140, 55, 'maize,beans,beef,tomatoes,onions', false, true),
            $this->row($u, 'Mukimo and Beef (Dinner)', 'dinner', 580, 32, 80, 14, 180, 50, 'mukimo,beef,potatoes,maize,peas', false, true),
            $this->row($u, 'Ugali and Goat Stew (Dinner)', 'dinner', 640, 36, 76, 20, 190, 55, 'ugali,goat,tomatoes,onions,garlic,spices', false, true),
            $this->row($u, 'Swahili Rice and Pilipili Chicken', 'dinner', 620, 38, 84, 14, 180, 55, 'rice,chicken,pilipili,coconut milk,spices', false, true),
            $this->row($u, 'Grilled Tilapia and Ugali', 'dinner', 570, 36, 76, 12, 170, 40, 'ugali,tilapia,lemon,garlic,herbs', false, true),
            $this->row($u, 'Rice and Green Grams (Dinner)', 'dinner', 480, 16, 88, 5, 85, 35, 'rice,green grams,coconut milk,garlic', true, true),
            $this->row($u, 'Egg Fried Rice', 'dinner', 480, 16, 78, 12, 110, 30, 'rice,eggs,onions,peas,soy sauce,garlic', false, false),
            $this->row($u, 'Chapati and Green Grams (Dinner)', 'dinner', 450, 14, 72, 8, 90, 35, 'chapati,green grams,coconut milk,onions', true, true),
            $this->row($u, 'Mixed Beans and Ugali', 'dinner', 500, 16, 88, 5, 80, 40, 'ugali,kidney beans,black beans,tomatoes,onions', true, true),
            $this->row($u, 'Boiled Maize and Bean Stew', 'dinner', 420, 14, 78, 4, 70, 45, 'maize,beans,tomatoes,onions', true, true),
            $this->row($u, 'Chapati and Kidney Beans', 'dinner', 470, 16, 74, 7, 90, 35, 'chapati,kidney beans,tomatoes,onions,spices', true, true),
            $this->row($u, 'Ugali and Mokimo (Nduma)', 'dinner', 490, 10, 88, 5, 75, 40, 'ugali,arrowroots,peas,maize', true, true),
            $this->row($u, 'Rice and Mutton Stew', 'dinner', 620, 34, 84, 18, 180, 55, 'rice,mutton,potatoes,tomatoes,onions,spices', false, true),
            $this->row($u, 'Chapati and Matumbo Stew', 'dinner', 510, 28, 66, 16, 130, 40, 'chapati,matumbo,tomatoes,onions,garlic', false, true),
            $this->row($u, 'Vegetable Biryani', 'dinner', 510, 12, 88, 10, 130, 50, 'rice,potatoes,peas,carrots,biryani spices,onions', true, false),
            $this->row($u, 'Lentil Soup with Ugali', 'dinner', 470, 16, 84, 6, 80, 35, 'ugali,lentils,tomatoes,onions,garlic,spices', true, true),
            $this->row($u, 'Spinach and Potato Stew with Rice', 'dinner', 460, 10, 86, 7, 85, 35, 'rice,spinach,potatoes,onions,tomatoes,garlic', true, false),
            $this->row($u, 'Pumpkin Soup and Bread', 'dinner', 320, 8, 56, 6, 75, 30, 'pumpkin,bread,onions,garlic,coconut milk', true, true),
            $this->row($u, 'Sweet Potato and Black Bean Bowl', 'dinner', 440, 14, 82, 5, 90, 30, 'sweet potatoes,black beans,onions,tomatoes,spices', true, false),
            $this->row($u, 'Ugali and Kunde (Dinner)', 'dinner', 440, 12, 78, 6, 70, 30, 'ugali,kunde,coconut milk,onions,tomatoes', true, true),
            $this->row($u, 'Beef and Vegetable Soup', 'dinner', 380, 26, 36, 14, 140, 40, 'beef,cabbage,carrots,onions,tomatoes,garlic', false, true),
            $this->row($u, 'Pasta and Vegetable Sauce', 'dinner', 440, 12, 76, 8, 100, 30, 'pasta,zucchini,tomatoes,onions,garlic,basil', true, false),
        ];
    }

    private function snackMeals(int $u): array
    {
        return [
            $this->row($u, 'Banana', 'snack', 89, 1, 23, 0, 15, 2, 'banana', true, true, 'Easy'),
            $this->row($u, 'Apple', 'snack', 80, 0, 21, 0, 30, 2, 'apple', true, false, 'Easy'),
            $this->row($u, 'Orange', 'snack', 62, 1, 15, 0, 20, 2, 'orange', true, false, 'Easy'),
            $this->row($u, 'Pineapple Slices', 'snack', 82, 1, 22, 0, 40, 5, 'pineapple', true, false, 'Easy'),
            $this->row($u, 'Mango Slices', 'snack', 99, 1, 25, 1, 50, 5, 'mango', true, true, 'Easy'),
            $this->row($u, 'Avocado', 'snack', 160, 2, 9, 15, 60, 2, 'avocado,salt,lemon', true, true, 'Easy'),
            $this->row($u, 'Yogurt', 'snack', 100, 5, 14, 2, 80, 2, 'yogurt,honey', true, false, 'Easy'),
            $this->row($u, 'Roasted Groundnuts', 'snack', 190, 8, 8, 16, 30, 15, 'groundnuts,salt', true, true, 'Easy'),
            $this->row($u, 'Roasted Maize', 'snack', 130, 4, 28, 2, 20, 15, 'maize,butter,salt', true, true, 'Easy'),
            $this->row($u, 'Boiled Maize', 'snack', 120, 3, 26, 2, 15, 30, 'maize,salt', true, true, 'Easy'),
            $this->row($u, 'Cassava Chips', 'snack', 160, 2, 34, 4, 30, 20, 'cassava,cooking oil,salt', true, true, 'Easy'),
            $this->row($u, 'Sweet Potato Chips', 'snack', 150, 2, 32, 4, 35, 25, 'sweet potatoes,cooking oil,salt', true, true, 'Easy'),
            $this->row($u, 'Mandazi Snack', 'snack', 180, 4, 30, 5, 40, 15, 'flour,sugar,coconut,milk', true, true, 'Easy'),
            $this->row($u, 'Samosa', 'snack', 180, 6, 22, 8, 60, 30, 'flour,mince,onions,spices', false, true, 'Medium'),
            $this->row($u, 'Bhajia', 'snack', 160, 5, 20, 7, 50, 20, 'potatoes,flour,onions,spices', true, true, 'Medium'),
            $this->row($u, 'Kebab', 'snack', 200, 14, 14, 10, 100, 30, 'minced beef,onions,garlic,bread,spices', false, true, 'Medium'),
            $this->row($u, 'Sausage', 'snack', 180, 10, 8, 14, 80, 10, 'sausage,cooking oil', false, false, 'Easy'),
            $this->row($u, 'Boiled Eggs', 'snack', 140, 12, 2, 10, 40, 10, 'eggs,salt', false, true, 'Easy'),
            $this->row($u, 'Fruit Salad', 'snack', 120, 2, 28, 1, 70, 10, 'banana,mango,pineapple,papaya,passion fruit', true, true, 'Easy'),
            $this->row($u, 'Mango Smoothie (Snack)', 'snack', 160, 3, 36, 1, 70, 5, 'mango,milk,honey', true, false, 'Easy'),
            $this->row($u, 'Banana Smoothie (Snack)', 'snack', 170, 5, 36, 2, 60, 5, 'banana,milk,honey,yogurt', true, false, 'Easy'),
            $this->row($u, 'Pineapple Smoothie', 'snack', 140, 2, 34, 1, 60, 5, 'pineapple,milk,honey', true, false, 'Easy'),
            $this->row($u, 'Avocado Smoothie (Snack)', 'snack', 190, 4, 22, 10, 70, 5, 'avocado,milk,honey,banana', true, false, 'Easy'),
            $this->row($u, 'Peanut Butter Smoothie (Snack)', 'snack', 250, 10, 30, 12, 80, 5, 'peanut butter,banana,milk', true, false, 'Easy'),
            $this->row($u, 'Yogurt Parfait (Snack)', 'snack', 220, 8, 36, 5, 100, 5, 'yogurt,granola,banana,honey', true, false, 'Easy'),
            $this->row($u, 'Granola Snack', 'snack', 200, 5, 34, 6, 80, 2, 'granola,milk,honey', true, false, 'Easy'),
            $this->row($u, 'Popcorn', 'snack', 100, 3, 18, 4, 30, 10, 'maize,cooking oil,salt', true, false, 'Easy'),
            $this->row($u, 'Coconut Slices', 'snack', 140, 1, 6, 13, 30, 2, 'coconut', true, true, 'Easy'),
            $this->row($u, 'Roasted Groundnuts (Salted)', 'snack', 190, 8, 8, 16, 30, 15, 'groundnuts,salt', true, true, 'Easy'),
            $this->row($u, 'Mixed Nuts', 'snack', 200, 6, 10, 16, 120, 2, 'cashews,groundnuts,almonds', true, false, 'Easy'),
            $this->row($u, 'Banana and Peanut Butter (Snack)', 'snack', 220, 7, 32, 10, 65, 3, 'banana,peanut butter', true, false, 'Easy'),
            $this->row($u, 'Apple and Peanut Butter', 'snack', 200, 6, 28, 10, 70, 3, 'apple,peanut butter', true, false, 'Easy'),
            $this->row($u, 'Carrot Sticks', 'snack', 50, 1, 12, 0, 30, 5, 'carrots,hummus', true, false, 'Easy'),
            $this->row($u, 'Cucumber Slices', 'snack', 40, 1, 8, 0, 30, 5, 'cucumber,lemon,salt', true, false, 'Easy'),
            $this->row($u, 'Vegetable Sticks with Dip', 'snack', 80, 3, 14, 2, 60, 10, 'carrots,cucumber,bell peppers,hummus', true, false, 'Easy'),
            $this->row($u, 'Bread and Butter (Snack)', 'snack', 180, 5, 26, 6, 40, 3, 'bread,butter', true, true, 'Easy'),
            $this->row($u, 'Bread and Jam (Snack)', 'snack', 170, 5, 32, 3, 45, 3, 'bread,jam', true, true, 'Easy'),
            $this->row($u, 'Bread and Honey (Snack)', 'snack', 175, 5, 34, 3, 50, 3, 'bread,honey', true, true, 'Easy'),
            $this->row($u, 'Chapati Snack', 'snack', 200, 5, 32, 6, 35, 15, 'chapati,butter', true, true, 'Easy'),
            $this->row($u, 'Pancake Snack', 'snack', 210, 6, 34, 6, 60, 15, 'flour,eggs,milk,honey', true, false, 'Easy'),
            $this->row($u, 'Fruit Smoothie Bowl (Snack)', 'snack', 200, 6, 40, 3, 100, 10, 'banana,mango,yogurt,granola', true, false, 'Easy'),
            $this->row($u, 'Yogurt and Honey', 'snack', 120, 6, 18, 2, 80, 2, 'yogurt,honey', true, false, 'Easy'),
            $this->row($u, 'Milk and Biscuits', 'snack', 220, 7, 34, 7, 70, 2, 'milk,biscuits', true, false, 'Easy'),
            $this->row($u, 'Sugar Cane', 'snack', 90, 0, 22, 0, 20, 2, 'sugar cane', true, true, 'Easy'),
            $this->row($u, 'Passion Fruit', 'snack', 70, 2, 16, 1, 25, 2, 'passion fruit', true, true, 'Easy'),
            $this->row($u, 'Guava Fruits', 'snack', 68, 3, 14, 1, 20, 2, 'guava', true, true, 'Easy'),
            $this->row($u, 'Papaya Slices', 'snack', 55, 1, 14, 0, 25, 5, 'papaya,lemon', true, true, 'Easy'),
            $this->row($u, 'Boiled Sweet Potatoes', 'snack', 130, 2, 30, 0, 30, 20, 'sweet potatoes,salt', true, true, 'Easy'),
            $this->row($u, 'Groundnut and Maize Mix', 'snack', 200, 7, 28, 8, 35, 5, 'groundnuts,maize', true, true, 'Easy'),
            $this->row($u, 'Mkate wa Sembe (Whole Wheat Bread)', 'snack', 160, 6, 28, 3, 50, 5, 'whole wheat bread,butter', true, true, 'Easy'),
            $this->row($u, 'Energy Bar', 'snack', 220, 8, 30, 8, 120, 2, 'oats,peanut butter,honey,chocolate', true, false, 'Easy'),
            $this->row($u, 'Protein Shake', 'snack', 200, 25, 18, 3, 150, 5, 'protein powder,milk,banana', false, false, 'Easy'),
            $this->row($u, 'Watermelon Slices', 'snack', 60, 1, 14, 0, 40, 3, 'watermelon', true, false, 'Easy'),
            $this->row($u, 'Cheese and Crackers', 'snack', 220, 8, 18, 14, 130, 3, 'cheese,crackers', false, false, 'Easy'),
            $this->row($u, 'Roasted Cashews', 'snack', 180, 5, 10, 14, 150, 5, 'cashews,salt', true, false, 'Easy'),
            $this->row($u, 'Date Fruits', 'snack', 140, 1, 36, 0, 80, 2, 'dates', true, false, 'Easy'),
            $this->row($u, 'Peanut Butter on Rice Cakes', 'snack', 200, 7, 24, 10, 80, 3, 'rice cakes,peanut butter', true, false, 'Easy'),
            $this->row($u, 'Tomato Slices', 'snack', 35, 2, 6, 0, 20, 3, 'tomatoes,salt,lemon', true, true, 'Easy'),
            $this->row($u, 'Corn on the Cob', 'snack', 130, 4, 28, 2, 20, 20, 'maize,butter,salt', true, true, 'Easy'),
            $this->row($u, 'Fried Cassava (Muhogo wa Kukaanga)', 'snack', 190, 2, 38, 5, 35, 20, 'cassava,cooking oil,salt', true, true, 'Easy'),
            $this->row($u, 'Mkate Mayai (Zanzibari Pizza Snack)', 'snack', 300, 14, 34, 12, 80, 20, 'flour,eggs,mince,onions,tomatoes', false, true, 'Medium'),
            $this->row($u, 'Mahamri', 'snack', 200, 4, 36, 6, 40, 30, 'flour,coconut milk,sugar,cardamom', true, true, 'Medium'),
            $this->row($u, 'Vitumbua (Rice Pancakes)', 'snack', 180, 4, 32, 4, 40, 25, 'rice flour,coconut milk,sugar', true, true, 'Medium'),
            $this->row($u, 'Karanga (Roasted Peanuts)', 'snack', 190, 8, 8, 16, 25, 10, 'peanuts,salt', true, true, 'Easy'),
            $this->row($u, 'Fried Plantains', 'snack', 160, 1, 34, 4, 40, 15, 'plantains,cooking oil,salt', true, true, 'Easy'),
            $this->row($u, 'Avocado and Lemon', 'snack', 150, 2, 8, 14, 60, 3, 'avocado,lemon,salt', true, true, 'Easy'),
            $this->row($u, 'Fruit Punch', 'snack', 100, 1, 24, 0, 50, 5, 'mango,pineapple,passion fruit juice', true, false, 'Easy'),
        ];
    }
}
